#ifndef ERRORS_H
#define ERRORS_H

enum _error {
  E_SUCCESS = 0,
  E_FILE_NOT_FOUND = -1,
  E_NO_FILE_SPECIFIED = -2,
  E_INVALID_SAM_LINE = -3,
  E_SAM_HEADER_LINE = -4,
  E_INVALID_ARGUMENT = -5,
  E_SAM_NON_SQ_HEADER = -6,
  E_CHROMOSOME_NOT_FOUND = -7,
  E_FILE_WRITING_FAILED = -8,
  E_INVALID_BED_LINE = -9,
  E_UNKNOWN_FILE_IO_ERROR = -10,
  E_INVALID_FASTA_FILE = -11,
  E_NEEDED_SEQUENCE_NOT_FOUND = -12,
  E_INVALID_FASTA_SEQUENCE_LENGTH = -13,
  E_CREATING_PIPE_FAILED = -14,
  E_NO_OPTIMAL_STRUCTURE_FOUND = -15,
  E_NO_STRUCTURE = -16,
  E_STRUCTURE_IS_INVALID = -17,
  E_INVALID_CANDIDATE_LINE = -18,
  E_INVALID_RANGE = -19,
  E_NO_MATURE_MI_RNA_FOUND = -20,
  E_NO_MATURE_MI_RNA = -21,
  E_NO_STAR_MI_RNA_FOUND = -22,
  E_FILE_DESCRIPTOR_TOO_LONG = -23,
  E_JAVA_SYSTEM_CALL_FAILED = -24,
  E_CREATING_REPORT_FAILED = -25,
  E_GNUPLOT_SYSTEM_CALL_FAILED = -26,
  E_LATEX_SYSTEM_CALL_FAILED = -27,
  E_CREATING_DIRECTORY_FAILED = -28,

  E_MALLOC_FAIL = -30,
  E_REALLOC_FAIL = -31,
  E_UNKNOWN = -99
};

struct _errordesc {
  int code;
  const char *message;
};
int print_error(int err);

#endif